### ISSUE TITLE
downloaded code from github as andoid payment sample but not working

### ISSUE THREAD

**Issue by manishshrotriya** [square/in-app-payments-android-quickstart#17]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.squareup.sdk.in-app-payments:card-entry:1.4.0.

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.squareup.sdk.in-app-payments:card-entry:1.2.0.

**Comment by StephenJosey** [comment]
Apologies for the delay here. Were you able to resolve this issue? If not, did you download the SDK successfully per the guide (https://developer.squareup.com/docs/in-app-payments-sdk/quick-start/step-2)?

**Comment by manishshrotriya** [comment]
I have downloaded sample from https://github.com/square/in-app-payments-android-quickstart but I am getting Unable to resolve dependency for ':app@debug/compileClasspath': error,  even I tried the following setup 
1. setup proxy to none 
2. disabled offline work 
3.  reinstalled android studio completely
4. removed firewall protection
but still stuck 
The main thing is the same code running in my one of colleague pc.

**Comment by manishshrotriya** [comment]
> Apologies for the delay here. Were you able to resolve this issue? If not, did you download the SDK successfully per the guide (https://developer.squareup.com/docs/in-app-payments-sdk/quick-start/step-2)?

This issue is fixed, it was because of old or corrupted JDK files.

**Comment by manishshrotriya** [comment]
I want to get payment for more than one retailer, so I have more than one of the application id and location id of individuals so i want to put these ids at run time and will decide which account will get paid.

**Comment by StephenJosey** [comment]
You should really be using the [OAuth API](https://developer.squareup.com/docs/oauth-api/overview) which will request access to individual merchants and generate unique access tokens for each one. That way you only need one application id, and when you are actually creating the payment you would use their access token so the money goes to the right account.

Please reach out on our new forums if you have additional questions: https://developer.squareup.com/forums/

**Comment by sadrakhamoshi** [comment]
I have the same problem in android studio 4.0.1. I changed the JDK but it's still not resolved what should I do?
